### ISSUE TITLE
Add Contributors section to README

### ISSUE THREAD

**Issue by shloka-gupta** [Ayushparikh-code/Face--Mask--Detection#19]
The Contributors section is a common section in the README. Adding it would be good.

**Comment by swathi-469** [comment]
I would like to work on this issue please assign me

**Comment by swathi-469** [comment]
Hi Ayushparikh-code/Face--Mask--Detection
 whether I need to create a branch or directly add in the main

**Comment by shloka-gupta** [comment]
Hey @swathi-469 ,

Okay so here are the steps:
1) you need to fork the repositry.
2) This will create a repository on your profile
3) Go to the forked repository and clone it.
4) Do changes in your local repository
5) Commit and push
6) Create a pull request.

**Comment by shloka-gupta** [comment]
@swathi-469 
Use PR - https://www.github.com/HarshCasper/Rotten-Scripts/tree/master/CONTRIBUTORS.md for reference.

**Comment by swathi-469** [comment]
Yeah i have made my pull request can you check it

**Comment by swathi-469** [comment]
Ohh kk mam Sure I will look into it and try to my pr
