### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by Ayushparikh-code** [Ayushparikh-code/Face--Mask--Detection#4]

**Comment by lachenlama** [comment]
Hello @Ayushparikh-code , anything specific to update in readme?

**Comment by kumarishalini6** [comment]
> _No description provided._

can i work on this issue?

**Comment by Ayushparikh-code** [comment]
> Hello @Ayushparikh-code , anything specific to update in readme?

Don't need any specific changes just Do changes as per your convenience to improve it , create pr I'll review it !

**Comment by Ayushparikh-code** [comment]
> > _No description provided._
> 
> can i work on this issue?

Sure

**Comment by kumarishalini6** [comment]
> > > _No description provided._
> > 
> > 
> > can i work on this issue?
> 
> Sure

Can you please assign this issue to me
